"""empty message

Revision ID: 198225b21b86
Revises: 07e38a917bbb
Create Date: 2020-06-15 21:02:12.374292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198225b21b86'
down_revision = '07e38a917bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('bookmarkId', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('imageAuthor', sa.String(length=255), nullable=True),
    sa.Column('writingGenre', sa.String(length=255), nullable=True),
    sa.Column('achievements', sa.String(length=255), nullable=True),
    sa.Column('evaluateAuthor', sa.Float(), nullable=True),
    sa.Column('evaluateBook', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('bookmarkId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
