"""empty message

Revision ID: 5c3b956a714c
Revises: fb3e81e4e40d
Create Date: 2020-05-20 16:08:27.743421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3b956a714c'
down_revision = 'fb3e81e4e40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('authorId', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('writingGenre', sa.String(length=255), nullable=True),
    sa.Column('achievements', sa.String(length=255), nullable=True),
    sa.Column('evaluate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('authorId')
    )
    op.create_table('bookmarks',
    sa.Column('bookmarkId', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('evaluate', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('registrationDate', sa.Integer(), nullable=True),
    sa.Column('expirationDate', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('bookmarkId')
    )
    op.create_table('books',
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('evaluate', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('bookId')
    )
    op.create_table('members',
    sa.Column('memberId', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('memberId')
    )
    op.create_table('orders',
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('evaluate', sa.Float(), nullable=True),
    sa.Column('registrationDate', sa.Integer(), nullable=True),
    sa.Column('expirationDate', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('orderId')
    )
    op.add_column('carts', sa.Column('cartId', sa.Integer(), nullable=False))
    op.drop_column('carts', 'membertId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('membertId', sa.INTEGER(), server_default=sa.text('nextval(\'"carts_membertId_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('carts', 'cartId')
    op.drop_table('orders')
    op.drop_table('members')
    op.drop_table('books')
    op.drop_table('bookmarks')
    op.drop_table('authors')
    # ### end Alembic commands ###
