"""empty message

Revision ID: d126e51b94d3
Revises: 9bac20d2e14a
Create Date: 2020-05-19 11:48:22.919883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd126e51b94d3'
down_revision = '9bac20d2e14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('phone', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'phone')
    # ### end Alembic commands ###
